name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      web:
        image: node:18
        ports:
          - 5173:5173
        options: >-
          --health-cmd "curl --fail http://localhost:5173 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build Vite app
        run: npm run build

      - name: Start Vite server
        run: npm run preview &
        env:
          PORT: 5173

      - name: Wait for Vite server to be ready
        run: npx wait-on http://localhost:5173

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
